# Generated by Django 5.0.7 on 2024-08-06 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicum2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
