# Generated by Django 5.0.7 on 2024-08-06 09:07

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicum2', '0002_alter_task_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date', 'assignee'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('created_at'), name='practicum2_project_name_created_at_unique'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('project'), name='practicum2_task_title_project_unique'),
        ),
    ]
