# Generated by Django 5.0.7 on 2024-08-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicum2', '0004_projectfile_project_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'verbose_name': 'ProjectFile', 'verbose_name_plural': 'ProjectFiles'},
        ),
    ]
